// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emztwtopyrsgapbzfvmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtenR3dG9weXJzZ2FwYnpmdm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTkzOTYsImV4cCI6MjA3NDQ5NTM5Nn0.1Qj8JNnt5nGrX4KNU5nemC8in5vkWvO_LrgdNinxenY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});